name: 💡 Feature Request
description: Suggest an idea for this project.
labels:
  - 'enhancement'
body:
  - type: input
    id: vscode-ibmi-testing-version
    attributes:
      label: IBM i Testing Version
      description: |
        What version of the `IBM i Testing` extension are you using?
      placeholder: |
        #.#.#
    validations:
      required: false
  - type: input
    id: rpgunit-version
    attributes:
      label: RPGUnit Version
      description: |
        What version of the `RPGUnit` library do you have installed on your IBM i?
      placeholder: |
        #.#.#
    validations:
      required: false
  - type: dropdown
    id: ibm-i-os-version
    attributes:
      label: IBM i OS Version
      description: |
        What version of IBM i are you running?
      options:
        - 7.6
        - 7.5
        - 7.4
        - 7.3
        - Older
      default: 0
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: |
        Describe the feature that you would like to see.
      placeholder: |
        Feature description
    validations:
      required: false