name: 💡 Feature Request
description: Suggest an idea for this project.
labels:
  - 'enhancement'
body:
  - type: markdown
    attributes:
      value: |
        ⭐ Before making a feature request, please make sure to check whether someone has already opened an issue for this [here](https://github.com/IBM/vscode-ibmi-testing/issues). ⭐
  - type: input
    id: vscode-ibmi-testing-version
    attributes:
      label: IBM i Testing Version
      description: |
        What version of the `IBM i Testing` extension are you using? This can be obtained from the `Extensions` view.
      placeholder: |
        #.#.#
    validations:
      required: false
  - type: input
    id: rpgunit-version
    attributes:
      label: RPGUnit Version
      description: |
        What version of the `RPGUnit` library do you have installed on your IBM i? This can be obtained from the library's text description.
      placeholder: |
        #.#.#
    validations:
      required: false
  - type: dropdown
    id: ibm-i-os-version
    attributes:
      label: IBM i OS Version
      description: |
        What version of IBM i are you running?
      options:
        - 7.6
        - 7.5
        - 7.4
        - 7.3
        - Older
      default: 0
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: |
        Describe the feature that you would like to see.
      placeholder: |
        Feature description

        Tip: You can attach any additional images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false